name: Build on commit
on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'
          #cache: 'gradle'

      - name: Build JS browser
        run: ./gradlew jsBrowserProductionWebpack

      - name: Build Webworker browser
        run: ./gradlew webworkerBrowserProductionWebpack

      - name: Arrange files
        run: |
          mkdir build/distributions
          rsync -a build/kotlin-webpack/js/productionExecutable/ build/distributions/
          rsync -a build/kotlin-webpack/webworker/productionExecutable/ build/distributions/
          rsync -a build/processedResources/js/main/ build/distributions/

      # If main branch update, deploy to gh-pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build/distributions # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch